name: Deploy Flutter Web

on:
  push:
    branches:
      - firebase_no_mocks_v2  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Specify your Flutter version
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: setup:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Run Cache Busting Build Script
        run: |
          chmod +x ./build-deploy.sh
          ./build-deploy.sh
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}