version: "3"

services:
  my_database:
    container_name: my_database
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"  # Expose the PostgreSQL port on the host
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  my_dart_application:
    container_name: my_dart_application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://my_user:my_password@host.docker.internal:5432/my_database?schema=public
    depends_on:
      my_database:
        condition: service_healthy

  prisma_studio:
    image: node:16
    container_name: prisma_studio
    working_dir: /app
    command: npx prisma studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://my_user:my_password@host.docker.internal:5432/my_database?schema=public
    volumes:
      - .:/app
    depends_on:
      - my_database