// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bU7JfgNRx5ZOJqnmNHKuvya3pLnDJ8Q',
    appId: '1:1087483483909:web:6d9daaef6a723b5841096c',
    messagingSenderId: '1087483483909',
    projectId: 'mesa-redonda-fb72e',
    authDomain: 'mesa-redonda-fb72e.firebaseapp.com',
    storageBucket: 'mesa-redonda-fb72e.appspot.com',
    measurementId: 'G-YVBY00F5GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM58a0ihCAmElW2o2Fo6AswHO37qKSDx0',
    appId: '1:1087483483909:android:15fd3d76a6a0701141096c',
    messagingSenderId: '1087483483909',
    projectId: 'mesa-redonda-fb72e',
    storageBucket: 'mesa-redonda-fb72e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlk83WpDsAWqaa4RqI4mxa5IYPiuZldek',
    appId: '1:1087483483909:ios:ff1d60b319f1a19541096c',
    messagingSenderId: '1087483483909',
    projectId: 'mesa-redonda-fb72e',
    storageBucket: 'mesa-redonda-fb72e.appspot.com',
    iosClientId: '1087483483909-almct9101dohm84eatahds8h1hss51ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlk83WpDsAWqaa4RqI4mxa5IYPiuZldek',
    appId: '1:1087483483909:ios:6a0634bc6d3c012441096c',
    messagingSenderId: '1087483483909',
    projectId: 'mesa-redonda-fb72e',
    storageBucket: 'mesa-redonda-fb72e.appspot.com',
    iosClientId: '1087483483909-ici1rplol63k3uul2tdtlc7s7bcfn467.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );

}