// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7T2ykod5kXw2DQBWT5-pXdbWQT4HGgo',
    appId: '1:224477049501:web:6c8033dae4732945725a74',
    messagingSenderId: '224477049501',
    projectId: 'vaca-esquizofrenica',
    authDomain: 'vaca-esquizofrenica.firebaseapp.com',
    storageBucket: 'vaca-esquizofrenica.appspot.com',
    measurementId: 'G-KCQYBCHG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkG785ePnbgsaQSwQY9jUddiAd8f97KKA',
    appId: '1:224477049501:android:3f8600f3c93729ea725a74',
    messagingSenderId: '224477049501',
    projectId: 'vaca-esquizofrenica',
    storageBucket: 'vaca-esquizofrenica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5cVvZYkGD0tK1-omgcfU77WfYRk8xfjs',
    appId: '1:224477049501:ios:c25944142ede147c725a74',
    messagingSenderId: '224477049501',
    projectId: 'vaca-esquizofrenica',
    storageBucket: 'vaca-esquizofrenica.appspot.com',
    iosClientId: '224477049501-17ep345dsnbkg87e1ike0oatrt2rgaee.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5cVvZYkGD0tK1-omgcfU77WfYRk8xfjs',
    appId: '1:224477049501:ios:1a54971227efa758725a74',
    messagingSenderId: '224477049501',
    projectId: 'vaca-esquizofrenica',
    storageBucket: 'vaca-esquizofrenica.appspot.com',
    iosClientId: '224477049501-h4s4olc4nbas720a0e4vuj9mqrcn2gd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );
}
